### ISSUE TITLE
Core kind do not get any kind 

### ISSUE THREAD

**Issue by Pierre-Mike** [plexsystems/konstraint#127]
In core.rego 

```
ressource = input.review.object
kind = resource.kind
```

But the kind for a gatekeeper object is 

```
{
    "kind": "AdmissionReview",
    "parameters": {},
    "review": {
        "kind": {
            "kind": "Pod",
            "version": "v1"
        },
        "object": {
            "metadata": {
                "name": "myapp",
                "namespace": ""
            },
            "spec": {
                "containers": []
            }
        }
    }
}
```

So kind should be 
```
kind = input.review.kind.kind
```

**Comment by jalseth** [comment]
This is intentional. The `input.review.object` [contains the full object](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#request) that was sent to the K8s API server, including the `Kind` and `apiVersion`. It was written this way so `core.kind` works both in Gatekeeper and outside of Gatekeeper, where `input.review.kind.kind` does not exist.
