### ISSUE TITLE
Flag to generate templates to v1 from v1beta1

### ISSUE THREAD

**Issue by eitah** [plexsystems/konstraint#304]
I noticed that OPA supports templates.gatekeeper.sh/v1 constraints (https://github.com/open-policy-agent/gatekeeper/pull/1926/files) but konstraint always generates templates.gatekeeper.sh/v1beta1. 

The reason why we speculate this is an issue is we still see activity coming from gatekeeper vs. the deprecated Kubernetes APIs, namely networking.k8s.io/v1beta1 and it's blocking us from being able to auto-migrate our cluster to a higher version of Kubernetes.

This might be related to the versions of OPA that both libraries are on, as I see that Gatekeeper uses OPA 0.39 but konstraint uses opa 0.40.

**Comment by jalseth** [comment]
Hi @eitah,

Konstraint generates v1beta1 Gatekeeper resources by default in order to keep compatibility with older versions that do not support v1 yet. If you want to generate v1 resources, you can use the `--constraint-template-version` flag.

This is not related to any other K8s resources using other APIs such as `networking.k8s.io/v1beta`.

**Comment by eitah** [comment]
Thanks! I'll close the issue.
