### ISSUE TITLE
Parameter abstraction causes constraint validation errors

### ISSUE THREAD

**Issue by dippynark** [plexsystems/konstraint#86]
With the parameter abstraction introduced recently https://github.com/plexsystems/konstraint/pull/80 I get validation errors when using [kpt's gatekeeper validation function](https://googlecontainertools.github.io/kpt/guides/consumer/function/catalog/validators/) to validate a set of manifests validate constraints:

```
kpt fn run ./configs --image gcr.io/kpt-functions/gatekeeper-validate
Error: check refs failed on module {libs.admission.k8s.gatekeeper.sh.PodDenyHostNetwork["lib_0"]}: disallowed ref data.parameters
error: exit status 1
```

I'm not sure if this is konstraint's responsibility (I'm very new to rego, so I don't really understand why the error is happening), but I thought it was as it seems to break backwards compatibility.

**Comment by jalseth** [comment]
This appears to be a case of two somewhat opinionated tools disagreeing. Konstraint and its libraries were built explicitly to allow for creating policies that could be tested locally with Conftest and then deployed to Gatekeeper without any changes. In order to emulate Gatekeeper's parameters functionality with Conftest, we must set `core.parameters` to `data.parameters` when the policy is evaluated outside of Gatekeeper. Of course, when running in Gatekeeper `data.parameters` is never actually referenced.

That validation tool appears to perform static analysis for validation and then attempts to output the Gatekeeper resources. However, when it attempts to create the ConstraintTemplate, its [upstream](https://github.com/GoogleContainerTools/kpt-functions-sdk/blob/6b27fd669c204ea37b1a1ea8e45b94c37f48379a/go/pkg/functions/gatekeeper/validate.go#L50) parsing logic is [hardcoded](https://github.com/open-policy-agent/frameworks/blob/0d37681951a45378118d97655d1e4829e3a706f6/constraint/pkg/client/client.go#L292-L295) to only allow references that start with `data.lib`. This restriction does not make sense in the context of Konstraint, so these two tools are incompatible in some scenarios, at least until that restriction is lifted on their end.

**Comment by dippynark** [comment]
Awesome cheers! Happy this isn't a Konstraint issue (after understand Rego a bit better now and with that explanation) -- I have worked around this for now by using the commit of Konstraint just before https://github.com/plexsystems/konstraint/pull/80 but hopefully that hardcoded restriction can be removed from OPA at some point

**Comment by dulltz** [comment]
@dippynark @jalseth 
After all, how do you work around this issue?
I would like to know if there is a better solution than manually removing the `data.parameters` from the generated ConstraintTemplate.

Now I make the following changes every time after running `konstraint create`.

```diff
$ git diff
diff --git a/constraints/overlays/staging/template_ApplicationTenant.yaml b/constraints/overlays/staging/template_ApplicationTenant.yaml
index d01f144..be187cc 100755
--- a/constraints/overlays/staging/template_ApplicationTenant.yaml
+++ b/constraints/overlays/staging/template_ApplicationTenant.yaml
@@ -57,10 +57,6 @@ spec:
           is_gatekeeper
       }

-      parameters = data.parameters {
-         not is_gatekeeper
-      }
-
       has_field(obj, field) {
           not object.get(obj, field, "N_DEFINED") == "N_DEFINED"
       }
```

**Comment by jalseth** [comment]
@dulltz If you don't use the parameters functionality, you can just remove it from your `lib.core` so it won't be included in the generated templates. Otherwise, you can open an issue in the upstream project to remove that hardcoded value.
