### ISSUE TITLE
Weird out-of-order creation of policy documentation

### ISSUE THREAD

**Issue by artis3n** [plexsystems/konstraint#87]
I don't think this is a bug with Konstraint, more of a user error or possible feature request. I'd like the documentation generated from our policies to be alphabetized - by either the title or by the policy ID if that is provided, since Konstraint auto-adds the `policyID` to the title when generating the documentation.

Right now, I have several policies under different directories and they generate into this, which is confusing to look at.
![image](https://user-images.githubusercontent.com/6969296/100659444-a4b08780-331e-11eb-86ef-665b0d7bd3fa.png)

I would like that to be:

```
Violations
- RALLY-0001
- RALLY-0002
- RALLY-0004
Warnings
- RALLY-0003
```

Any way I can make that happen? If not, what type of feature request is this? :)

**Comment by jalseth** [comment]
Hey @artis3n ! [Currently](https://github.com/plexsystems/konstraint/blob/279945ba1f170f4bd8d6c9a2f586a781736ace7c/internal/rego/rego.go#L297-L299) the sorting is based on the file name, not the policy title. I think it makes sense to sort the documentation based on the title, which should be easy to add. If you have the time, I'd welcome a PR!

**Comment by artis3n** [comment]
I'll look into it this week!

**Comment by artis3n** [comment]
How would you like to see this:
- Change the default sorting to be _something else_ (based on policy ID or based on policy ID + title, or ...)
- Add a cli flag to change sorting between one of several options (default = as-is, or ?)

**Comment by jalseth** [comment]
Since this only affects documentation generation and not anything related to how the policies are generated or enforced, I think it's safe to just change the default. Since we can't be sure that a policy has a policy ID, they should be sorted [after](https://github.com/plexsystems/konstraint/blob/279945ba1f170f4bd8d6c9a2f586a781736ace7c/internal/commands/document.go#L128-L131) the policy ID is merged with the title.
